services:
    db:
        image: postgres:16.4-alpine
        environment:
            POSTGRES_USER: ${APP_SECRETS__POSTGRES_ADMIN_USER}
            POSTGRES_PASSWORD: ${APP_SECRETS__POSTGRES_ADMIN_PASSWORD}
            POSTGRES_DB: ${APP_SECRETS__POSTGRES_ADMIN_DB}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
    pgadmin:
        image: dpage/pgadmin4:latest
        depends_on:
            db:
                condition: service_healthy
        environment:
            PGADMIN_DEFAULT_EMAIL: ${APP_SECRETS__PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${APP_SECRETS__PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_ADDRESS: "0.0.0.0"
        ports:
            - "8081:80"
        volumes:
            - pgadmindata:/var/lib/pgadmin
    webapp:
        image: ghcr.io/hunterjw/blogdotnet:latest
        depends_on:
            db:
                condition: service_healthy
        environment:
            ConnectionStrings__BlogDotNet: ${APP_SECRETS__POSTGRES_CONNECTION_STRING}
            BlogDotNet__Blog__Title: ${APP_SECRETS__BLOG_TITLE}
            BlogDotNet__FileScanner__BasePath: "/blogdotnet/files"
            BlogDotNet__Migrations__PostgresAdminConnectionString: ${APP_SECRETS__POSTGRES_ADMIN_CONNECTION_STRING}
            BlogDotNet__Migrations__Database: ${APP_SECRETS__POSTGRES_DB}
            HTTP_PORTS: 80
        ports:
            - "8082:80"
        build: 
            context: ./src
            dockerfile: ./BlogDotNet.BlazorWebApp/Dockerfile
        volumes:
            - ${APP_SECRETS__BLOG_FILES}:/blogdotnet/files

volumes:
    pgdata:
    pgadmindata: